### ISSUE TITLE
Native Error

### ISSUE THREAD

**Issue by krizmatic** [qbcore-framework/qb-smallresources#11]
A native error is showing up in console while using player hostage. But there is no issue with the script and it is working fine.
![image](https://user-images.githubusercontent.com/58721529/125099413-9bc63680-e0f5-11eb-8fa7-daf43d9de548.png)

**Comment by BerkieBb** [comment]
@krizmatic Do you know when the error showed up?

**Comment by krizmatic** [comment]
Dont remember actually. I have solved it by adding TakeHostage (https://github.com/rubbertoe98/FiveM-Scripts/tree/master/TakeHostage) to this script.

**Comment by BerkieBb** [comment]
Alright, I'll use Diffchecker to check the difference because TakeHostage is almost the same

**Comment by BerkieBb** [comment]
Okay well it is not the same, then I'll check if I can just fix it

**Comment by BerkieBb** [comment]
Well I found the problem, there is no client side for the hostage...

**Comment by krizmatic** [comment]
Yeah, that's causing the issue.

**Comment by BerkieBb** [comment]
Hostage has been removed for now, can be added in the future
