### ISSUE TITLE
parachute bcakpack doesn't get from the back after landing

### ISSUE THREAD

**Issue by zeemkarry** [qbcore-framework/qb-smallresources#112]
Parachute gets permanently register as selected bag in clothing menu.
need to go to clothing shop to remove parachute as bag

**Comment by TrueSunnyD** [comment]
Essentially what he is saying is that after you use the parachute, the parachute doesn't disappear off your back after landing.

**Comment by vulthrax** [comment]
type /resetparachute in chat
