### ISSUE TITLE
push vehicle

### ISSUE THREAD

**Issue by Skillgjii** [qbcore-framework/qb-smallresources#116]
push vehicle arent working, doesnt mather what value i put in config minimum dammage. 
no errors

**Comment by Demo4889** [comment]
Works completely fine for me. I can even push vehicles that are completely exploded beyond repair.

**Comment by b1uedr4gon** [comment]
can confirm this works fine for me also , only once vehicle has exploded , i can't push a perfectly fine vehicle but then why would i.

**Comment by Demo4889** [comment]
I actually just added `and GetVehicleEngineHealth(Vehicle.Vehicle) >= 0` to the end of line 56 so it will check if the engine health is above 0 considering completely destroyed is a negative number and goes down to -4000 when the car is exploded. So if the car is exploded, you cannot push it.

`            if IsVehicleSeatFree(Vehicle.Vehicle, -1) and not IsPedSwimming(ped) and not IsPedSwimmingUnderWater(ped) and GetVehicleEngineHealth(Vehicle.Vehicle) <= Config.DamageNeeded and GetVehicleEngineHealth(Vehicle.Vehicle) >= 0  then
`

**Comment by IIMKII** [comment]
Line 18 - replace this - makes it actually work with config
`if not IsEntityAttachedToEntity(ped, veh) and IsVehicleSeatFree(veh, -1) and GetVehicleEngineHealth(veh) <= Config.DamageNeeded then`

Line 42 - makes pushing only work when pressing down W
```

if IsControlPressed(0, 32) then
                            SetVehicleForwardSpeed(veh, isInFront and -1.0 or 1.0)
                        end
```

**Comment by gemglove** [comment]
> Line 18 - replace this - makes it actually work with config `if not IsEntityAttachedToEntity(ped, veh) and IsVehicleSeatFree(veh, -1) and GetVehicleEngineHealth(veh) <= Config.DamageNeeded then`
> 
> Line 42 - makes pushing only work when pressing down W
> 
> ```
> 
> if IsControlPressed(0, 32) then
>                             SetVehicleForwardSpeed(veh, isInFront and -1.0 or 1.0)
>                         end
> ```

You are a G

**Comment by Fristiipatron** [comment]
Can anyone send me a new vehiclepush lua? mine isnt working
also not good at dev

**Comment by NCHubScammers** [comment]
Its not working for me also
