### ISSUE TITLE
Changing seatbelt key isnt working

### ISSUE THREAD

**Issue by vulthrax** [qbcore-framework/qb-smallresources#131]
Hi, im trying to change the seatbelt key for qb-smallresources, i found in the client seatbelt.lua on line 33 the following text i changed it from B to G.
Line33:RegisterKeyMapping('toggleseatbelt', 'Toggle Seatbelt', 'keyboard', 'G')

Allready done a full restart and it doesnt change the key.

**Comment by meistroburger** [comment]
You can change the seatbelt in the Settings > Key Binds > FiveM

**Comment by BrodieLawson** [comment]
The key will change for all new people but whatever key you originally joined the server with it set as is what it will be saved as, to reset this just clear your cache or citizen folder.
