### ISSUE TITLE
error in console

### ISSUE THREAD

**Issue by jasini1609** [qbcore-framework/qb-smallresources#174]
i always get this error 

[script:qb-smallresou] SCRIPT ERROR: @qb-smallresources/server/main.lua:29: attempt to perform arithmetic on a nil value (field 'uses')

**Comment by d-w00d** [comment]
Can confirm as well with the fresh pull

**Comment by MonkeyWhisper** [comment]
Not getting this at all.

**Comment by d-w00d** [comment]
Have you used a Harness? use a harness it usually appears

**Comment by ALFAMAS** [comment]
> i always get this error
> 
> [script:qb-smallresou] SCRIPT ERROR: @qb-smallresources/server/main.lua:29: attempt to perform arithmetic on a nil value (field 'uses')

I Get the Same Error

**Comment by Newtonzz** [comment]
Not enough info provided/no template used.

**Comment by iboss21** [comment]
It happened when I used a harness. 
script:qb-smallresou] SCRIPT ERROR: @qb-smallresources/server/main.lua:29: attempt to perform arithmetic on a nil value (field 'uses')

**Comment by iboss21** [comment]
[script:qb-smallresou] SCRIPT ERROR: @qb-smallresources/server/entities.lua:6: attempt to index a nil value (global 'Config')
