### ISSUE TITLE
[BUG] Racing Harness

### ISSUE THREAD

**Issue by LateNightRP** [qbcore-framework/qb-smallresources#192]
**__Issue:__**
Noticed when using the Racing Harness an error code will show up in server console.  

**__Bug Steps:__**
1- Use Racing Harness in inventory
2- When you use Racing Harness an error code will show up in server console.
3- When you remove Racing Harness, it will not remove HUD icon. 

**__Photo:__**
https://cdn.discordapp.com/attachments/859528707814981653/944797065031073803/qb-racingseatbelt.PNG

**Comment by MonkeyWhisper** [comment]
Because the harness was not given properly, maybe by a command or a crafting table.

**Comment by Goykz** [comment]
> Because the harness was not given properly, maybe by a command or a crafting table.

Can you explain more as doing giveitem causes this to happen aswell.

**Comment by erikmeyer08** [comment]
This pull request will resolve the issue! @GhzGarage 
https://github.com/qbcore-framework/qb-smallresources/pull/242
