### ISSUE TITLE
Infinity Armor

### ISSUE THREAD

**Issue by pedroalmeida91** [qbcore-framework/qb-smallresources#195]
I run out of armor and whenever I leave and enter the server, the armor is new

**Comment by jay-mars** [comment]
me too

**Comment by BerkieBb** [comment]
Still an issue with the latest qb-ambulancejob, qb-policejob and qb-smallresources?

**Comment by reymondgomez** [comment]
I have the same problem

**Comment by Pyth3rEx** [comment]
double with #293

**Comment by Pyth3rEx** [comment]
Referring the fix for the issue:
https://github.com/qbcore-framework/qb-core/issues/950#issuecomment-1964858534
