### ISSUE TITLE
[BUG] Can't tackle even after updating  

### ISSUE THREAD

**Issue by BLUEx154** [qbcore-framework/qb-smallresources#200]
I don't have any errors I just can't tackle does anyone know why?

**Comment by HestonB** [comment]
I'm having the same issue. Anyone know what's wrong?

**Comment by ericb160** [comment]
same :(

**Comment by LemonzPCMR** [comment]
What is the default key? I can see the function is still in the script but for the life of me i cant find a keybind calling the function.

**Comment by HestonB** [comment]
I believe it's left alt

**Comment by milotiro95** [comment]
The defaut bind is left alt but as usual in QBCore the binds are fucked up. You need to go in echap / touch configuration / fivem to change it or if IsControlJustPressed(1, 19) then change in in the escript for the key you want for.

Left alt is already use for qb-target and talking over the radio. 3 fucking binds for 1 key lol.
