### ISSUE TITLE
How do I disable the disabling of police?

### ISSUE THREAD

**Issue by MistakingManx** [qbcore-framework/qb-smallresources#204]
I tried messing with the config, but I still don't get the police when I hit someone, I'm using the QBCore template on txAdmin.

I want people to get police when they murder people.

**Comment by jaylac2000** [comment]
go to qb-smallresources/config.lua and delete all the police peds from in there

**Comment by RafaElZgz** [comment]
> go to qb-smallresources/config.lua and delete all the police peds from in there

That won´t work.

**Comment by zulsyazwan** [comment]
no update yet right?

**Comment by charj** [comment]
I've created a PR which adds config items for the dispatch services.
https://github.com/qbcore-framework/qb-smallresources/pull/268

**Comment by MistakingManx** [comment]
Bit longer than 60 days, github actions.
