### ISSUE TITLE
Getting Errors

### ISSUE THREAD

**Issue by GhostLegionRP** [qbcore-framework/qb-smallresources#205]
[script:qb-smallresou] SCRIPT ERROR: @qb-smallresources/server/entities.lua:6: attempt to index a nil value (global 'Config')
[script:qb-smallresou] > handler (@qb-smallresources/server/entities.lua:6)

Entities:
-- Blacklisting entities can just be handled entirely server side with onesync events
-- No need to run coroutines to supress or delete these when we can simply delete them before they spawn
AddEventHandler("entityCreating", function(handle)
    local entityModel = GetEntityModel(handle)

    if Config.BlacklistedVehs[entityModel] or Config.BlacklistedPeds[entityModel] then
        CancelEvent()
    end
end)

**Comment by codi47** [comment]
did u find out?

**Comment by GhostLegionRP** [comment]
> did u find out?

No sorry

**Comment by BerkieBb** [comment]
You messed up your config

**Comment by tomb2478** [comment]
has anyone solved this issue ?

**Comment by osdaohdph** [comment]
![image](https://github.com/qbcore-framework/qb-smallresources/assets/140257054/b525b7a9-e44c-4cee-a4a9-7c69fbca89b8)

**Comment by SaschaB88** [comment]
> ![image](https://user-images.githubusercontent.com/140257054/282258857-b525b7a9-e44c-4cee-a4a9-7c69fbca89b8.png) Hello I I have a problem. Can anyone help me resolve this error?

I have the Same issue here

**Comment by veebrazy** [comment]
How can I fix this issue??
