### ISSUE TITLE
Doesn't do animations

### ISSUE THREAD

**Issue by SeriumTW** [qbcore-framework/qb-smallresources#207]
In my server when I eat or drink it doesn't do animations. Why?

**Comment by jaylac2000** [comment]
do you have a emote script such as [dpemotes](https://github.com/qbcore-framework/dpemotes)?

**Comment by champstamp** [comment]
> do you have a emote script such as [dpemotes](https://github.com/qbcore-framework/dpemotes)?

I use a different animation script, how would I trigger it? it still has the same animations.

**Comment by jaylac2000** [comment]
Depends how it's triggered by that script. Is it open source?

**Comment by Medit8z** [comment]
> do you have a emote script such as [dpemotes](https://github.com/qbcore-framework/dpemotes)?

I am using dpemotes and i have the same issue. Never had this till i updated all my qb file to the newest version. Any ideas?
