### ISSUE TITLE
how to disable auto engine start please

### ISSUE THREAD

**Issue by bimbolaki** [qbcore-framework/qb-smallresources#215]
here is all that is said I want to deactivate the auto start when the plyer gets into a vehicle.
I searched in all the files but I can't find it can you tell me where to find this function :) thank you in advance

**Comment by RafaElZgz** [comment]
I am looking for this too, could only see some related code in seatbelt.lua.

**Comment by GhostLegionRP** [comment]
push

**Comment by i-kulgu** [comment]
> here is all that is said I want to deactivate the auto start when the plyer gets into a vehicle. I searched in all the files but I can't find it can you tell me where to find this function :) thank you in advance

This needs to be done in qb-vehiclekeys.
You need to adjust the SetVehicleEngineOn native : https://docs.fivem.net/natives/?_0x2497C4717C8B881E
