### ISSUE TITLE
Seatbelt -> HUD Error

### ISSUE THREAD

**Issue by bosskitz** [qbcore-framework/qb-smallresources#23]
When a player has its seatbelt on and got thrown out from a car crash, the next time the player goes inside a vehicle,

1. The player's seatbelt is automatically turned on but the HUD says not yet on seatbelt and HUD is not lit.
2. If the player rides a bike/motorcycle, player can no longer get out and needs to reconnect in order to continue.
3. When you use the item "Harness" and you get out of the car, you have to press seatbelt again to get out as putting harness on will trigger seatbelt but getting it off won't turn off seatbelt.

Thank you!
By the way, where can I donate/support for QBCore?

**Comment by BerkieBb** [comment]
I will look into these things and push the required changes

For support you can join the discord: https://discord.gg/qbcore

**Comment by bosskitz** [comment]
> I will look into these things and push the required changes
> 
> For support you can join the discord: https://discord.gg/qbcore

Thanks brother, yeah. I bought a couple of beers for Kakator :D

**Comment by thatsimpressive** [comment]
#32 - That could possibly solve an issue on that list.

**Comment by bosskitz** [comment]
> #32 - That could possibly solve an issue on that list.

Indeed solved the issue. Thanks brother!

**Comment by PumaPowerPT** [comment]
i still have that problem
