### ISSUE TITLE
Got error 

### ISSUE THREAD

**Issue by hichay** [qbcore-framework/qb-smallresources#230]
![image](https://user-images.githubusercontent.com/9911085/171830218-09308309-b75f-4f6b-849c-6102be977f7a.png) Error with ignore

**Comment by EinS4ckZwiebeln** [comment]
You could've at least shown the whole error lol

**Comment by hichay** [comment]
> You could've at least shown the whole error lol

that is the whole error. lol it come from the ignore delete vehicle?

**Comment by TheiLLeniumStudios** [comment]
@hichay as @EinS4ckZwiebeln mentioned, you should've shown the whole error that mentions which file in the script and which line is throwing the error. It doesn't make sense to search the whole script and try to figure out from where this error is originating from
