### ISSUE TITLE
[BUG] Inconsistencies with weapon drawing

### ISSUE THREAD

**Issue by EinS4ckZwiebeln** [qbcore-framework/qb-smallresources#231]
**Describe the bug**
When you put your already drawn weapon back and you equip it again while the put-back animation is still going on the script logic breaks. If you try then to draw the very same weapon nothing happens, it won't draw. You have to draw it again in order to make it work.

**To Reproduce**
1. Draw any weapon (only tried pistols but I suppose this applies to any weapon)
2. Put it back/Enter put-back animation
3. Then while still putting the weapon back pull it out again
4. Finished! Now you have to draw it twice to actually function

**Expected behavior**
You should only have to draw it once to properly function.

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] 
 --> Latest commit (#226)

 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target]
--> No. But I tried this using regular qb-inventory.

 - Have you renamed `qb-` to something custom? [e.g. yes/no]
 --> No.

**Comment by b1uedr4gon** [comment]
we have noticed this same problem also and it does make drawing a gun inconsistent
