### ISSUE TITLE
[BUG] cant fight/attack when use joint and press "x"

### ISSUE THREAD

**Issue by xenfovn** [qbcore-framework/qb-smallresources#238]
[BUG] cant fight/attack when use joint and press "x"

use joint and wait 5 sec , press x , we cant fight , it is related to dpemotes

**Comment by xenfovn** [comment]
i pushed pr to fixed it https://github.com/qbcore-framework/dpemotes/pull/25

**Comment by Ford1337** [comment]
@xenfovn Thank you alot for this fix, I used it in my dpemotes ! 👍
