### ISSUE TITLE
Police weapon draw

### ISSUE THREAD

**Issue by glitchychoppa** [qbcore-framework/qb-smallresources#240]
**Describe the bug**
Normally, people in the police profession have a faster weapon draw animation than normal players, but when I looked through the codes, I couldn't find a line of code that would question them as a cop.

**To Reproduce**
Give yourself a police job and you will see that the animation is not separate from the regular players
qb-smallresources | client | weapdraw.lua

**Expected behavior**
Faster draw animation for cops on every server

**Screenshots**
Nope

**Questions (please complete the following information):**
 - When you last updated: [last mounth]
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target]  no
 - Have you renamed `qb-` to something custom? yes

**Additional context**
Nope

**Comment by glitchyishere** [comment]
Have you renamed qb- to something custom? no

**Comment by glitchyishere** [comment]
Have you renamed qb- to something custom? no

**Comment by Holidayy95** [comment]
This was changed ages ago with this Commit

https://github.com/qbcore-framework/qb-smallresources/commit/1b56ec0a84e2d1e6fcbca658f46abf0ad3907bcb

If you want it to use the old policejob check, just undo the changes

**Comment by bosskitz** [comment]
Would love to see this added -> For players with "police" job should have a faster weapon draw anim.

**Comment by ericb160** [comment]
Same problem here.

**Comment by JamieT0001** [comment]
There is absloutely no reason for this to happen except i they are wearing a holster. Which is possibly the case if you are wearing a uniform.
