### ISSUE TITLE
auto gun in car

### ISSUE THREAD

**Issue by arroval** [qbcore-framework/qb-smallresources#244]
Hello, I have a problem with weapons. She selects it directly when I get into a car. Has anyone had the same problem and know how to fix it?

**Comment by singh-manavv** [comment]
Just add this in a client thread somewhere `DisablePlayerVehicleRewards(PlayerPedId())`

**Comment by ALFAMAS** [comment]
> 

not working

**Comment by singh-manavv** [comment]
@ALFAMAS did you run it in a while loop thread ?

**Comment by ALFAMAS** [comment]
> @ALFAMAS did you run it in a while loop thread ?

While Loop

**Comment by ALFAMAS** [comment]
> @ALFAMAS did you run it in a while loop thread ?

Can you send a Screenshot Example

**Comment by MilyonJames** [comment]
> Just add this in a client thread somewhere `DisablePlayerVehicleRewards(PlayerPedId())`

It should be `DisablePlayerVehicleRewards(PlayerId())` and not the ped entity. But I just ran into some issues with it, that's why i'm here now.

**Comment by ALFAMAS** [comment]
any Fix
