### ISSUE TITLE
[BUG] Animations won't work

### ISSUE THREAD

**Issue by Caprea27** [qbcore-framework/qb-smallresources#245]
**Describe the bug**
Eat, drink and several scripted animations won't work not even after downloading the latest dpemotes and adding it to the database.

What can i do?

**Comment by Medit8z** [comment]
I am also having this same issue. I didnt before i updated all my qb scripts to the newest version. Any ideas?

**Comment by woofertv** [comment]
You need to modify in dpemotes/config.lua, line 48
`    Framework = false,
`
to
`    Framework = "qb-core",
`
This will enable them again. Not a qb-smallresources issue.

**Comment by BerkieBb** [comment]
Use this https://github.com/qbcore-framework/dpemotes and there is no Framework config option
