### ISSUE TITLE
Seatbelt buckle/unbuckle when pause menu is open

### ISSUE THREAD

**Issue by woerki** [qbcore-framework/qb-smallresources#246]
Especially when you put the button to buckle/unbuckle on the left mouse button and then you're in pause menu to set a GPS, then you will get buckle/unbuckle.

An IF "pause menu is open" (i don't know the correct syntax) is needed that you only can buckle/unbuckle when pause menu is NOT open.

**Comment by ChatDisabled** [comment]
So each time someone wants to do a drive by, they will also trigger their seatbelt? Eh?
