### ISSUE TITLE
[BUG] weapon draw

### ISSUE THREAD

**Issue by jaylac2000** [qbcore-framework/qb-smallresources#247]
**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.

when you are a cop and you pull your gun from a holster than you /logout and switch to another character who isn't a cop such as a criminal character, that character still poses as if he's still a cop when pulling out a weapon

**To Reproduce**
1. read above^^

**Expected behavior**

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] fully updated version
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] n/a
 - Have you renamed `qb-` to something custom? [e.g. yes/no] no

**Additional context**

**Comment by singh-manavv** [comment]
the script only checks if the player is wearing a holster or not , to play the holster animation , so if the player is wearing a holster component, then the script will perform the holster animation or else normal animation. There's no checks for policejob in the script.
