### ISSUE TITLE
[BUG] Recoil Error

### ISSUE THREAD

**Issue by TehGuardian** [qbcore-framework/qb-smallresources#253]
**Describe the bug**
(https://i.imgur.com/zrvE6bm.png)
Recoil not working after using latest

**To Reproduce**
1. Load a gun 
2. Shoot
3. Get error and no recoil

**Comment by Temouchenty** [comment]
try the old function 

CreateThread(function()
	while true do
		local ped = PlayerPedId()
		if IsPedShooting(ped) and not IsPedDoingDriveby(ped) then
			local _,wep = GetCurrentPedWeapon(ped)
			_,cAmmo = GetAmmoInClip(ped, wep)
			if recoils[wep] and recoils[wep] ~= 0 then
				local tv = 0
				if GetFollowPedCamViewMode() ~= 4 then
					repeat
						Wait(0)
						local p = GetGameplayCamRelativePitch()
						SetGameplayCamRelativePitch(p+0.1, 0.2)
						tv = tv+0.1
					until tv >= recoils[wep]
				else
					repeat
						Wait(0)
						local p = GetGameplayCamRelativePitch()
						if recoils[wep] > 0.1 then
							SetGameplayCamRelativePitch(p+0.6, 1.2)
							tv = tv+0.6
						else
							SetGameplayCamRelativePitch(p+0.016, 0.333)
							tv = tv+0.1
						end
					until tv >= recoils[wep]
				end
			end
		end
		Wait(0)
	end
end)

**Comment by Temouchenty** [comment]
try the old function

`CreateThread(function()
	while true do
		local ped = PlayerPedId()
		if IsPedShooting(ped) and not IsPedDoingDriveby(ped) then
			local _,wep = GetCurrentPedWeapon(ped)
			_,cAmmo = GetAmmoInClip(ped, wep)
			if recoils[wep] and recoils[wep] ~= 0 then
				local tv = 0
				if GetFollowPedCamViewMode() ~= 4 then
					repeat
						Wait(0)
						local p = GetGameplayCamRelativePitch()
						SetGameplayCamRelativePitch(p+0.1, 0.2)
						tv = tv+0.1
					until tv >= recoils[wep]
				else
					repeat
						Wait(0)
						local p = GetGameplayCamRelativePitch()
						if recoils[wep] > 0.1 then
							SetGameplayCamRelativePitch(p+0.6, 1.2)
							tv = tv+0.6
						else
							SetGameplayCamRelativePitch(p+0.016, 0.333)
							tv = tv+0.1
						end
					until tv >= recoils[wep]
				end
			end
		end
		Wait(0)
	end
end)
`

**Comment by Wafflzdev** [comment]
> **Describe the bug** (https://i.imgur.com/zrvE6bm.png) Recoil not working after using latest
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Load a gun
> 2. Shoot
> 3. Get error and no recoil

Same and I just installed QBCore about 20min ago

**Comment by DannysRP** [comment]
I've noticed this error as well

**Comment by SweetsMarie** [comment]
Me too. We can't use the guns unless we spawn them in.

**Comment by Howsn** [comment]
I fixed this by changing all 3 lines with "tv += 0.1" to "tv = 0.1 +tv".

CreateThread(function()
	while true do
		local ped = PlayerPedId()
		if IsPedShooting(ped) and not IsPedDoingDriveby(ped) then
			local _, wep = GetCurrentPedWeapon(ped)
			_, cAmmo = GetAmmoInClip(ped, wep)
			if recoils[wep] and recoils[wep] ~= 0 then
				-- luacheck: ignore
				local tv = 0
				if GetFollowPedCamViewMode() ~= 4 then
					repeat
						Wait(0)
						local p = GetGameplayCamRelativePitch()
						SetGameplayCamRelativePitch(p+0.1, 0.2)
						tv = 0.1 +tv
					until tv >= recoils[wep]
				else
					repeat
						Wait(0)
						local p = GetGameplayCamRelativePitch()
						if recoils[wep] > 0.1 then
							SetGameplayCamRelativePitch(p+0.6, 1.2)
							tv = 0.6 +tv
						else
							SetGameplayCamRelativePitch(p+0.016, 0.333)
							tv = 0.1 +tv
						end
					until tv >= recoils[wep]
				end
			end
		end
		Wait(0)
	end
end)

**Comment by i-kulgu** [comment]
This should be fixed with the latest version.
Download the latest version and try it out.
