### ISSUE TITLE
harness still not fixed [BUG]

### ISSUE THREAD

**Issue by FrequencyRoleplay** [qbcore-framework/qb-smallresources#264]
[script:qb-smallresou] SCRIPT ERROR: @qb-smallresources/server/main.lua:27: attempt to index a string value (field 'info')    

looked into what it was and related back to this 

      Player.PlayerData.items[item.slot].info.uses = 19

**Comment by midz8** [comment]
Yeah I just updated my small resources a few days ago and still get this error when using the harness
