### ISSUE TITLE
[BUG] Weapon draw not working for police

### ISSUE THREAD

**Issue by divide29** [qbcore-framework/qb-smallresources#269]
**Describe the bug**
Hi,
through the new commit the weapon draw function is not working. I've tested all belts and it's just use the normal civilian weapon draw. No errors or something else.

**Expected behavior**
Weapon draw functional if using right belt

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] 1 day before
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] no
 - Have you renamed `qb-` to something custom? [e.g. yes/no] no

**Comment by N4PK1NZZz** [comment]
https://github.com/qbcore-framework/qb-smallresources/pull/272

**Comment by raydenjj** [comment]
> #272

I do this and don't change nothing... :/

**Comment by amantu-qbit** [comment]
@divide29  Still having issues?

**Comment by divide29** [comment]
@amantu-qbit I'm not longer in the fivem scene active, so i can't test it. I'm sorry.
