### ISSUE TITLE
[BUG]car belts

### ISSUE THREAD

**Issue by alfiswielki** [qbcore-framework/qb-smallresources#279]
Welcome!
Even though I have my seatbelt on , a character can fall out through the windscreen. Where can this be changed?

**Comment by Nodeee** [comment]
do you know how to fix it? i have the same issue

**Comment by BrandsPickled** [comment]
If its a fast vehicle you will need to use a harness

**Comment by Zack3267** [comment]
Same issue. Just wanna be able to adjust the speed at which I head out through the windshield with seatbelt on or seatbelt off. Any fixes for this so far?

**Comment by amantu-qbit** [comment]
@alfiswielki Adjust the Speed on the file
