### ISSUE TITLE
Script error Handsup[BUG]

### ISSUE THREAD

**Issue by KSJDiamondGaming** [qbcore-framework/qb-smallresources#282]
When pressing X for hands p getting this error. when either getting up from seats. or just random for surrender, any actions. using latest version of qb core and resources also https://github.com/TayMcKenzieNZ/dpemotes. 
![a](https://user-images.githubusercontent.com/83096833/192047356-7ffa00a4-c2c5-4b1d-a865-647476671a1d.png)

**Comment by adweex** [comment]
Having the same bug except i got no errors. However it not works.

**Comment by amantu-qbit** [comment]
@KSJDiamondGaming Still having the issue?

**Comment by adweex** [comment]
> @KSJDiamondGaming Still having the issue?

Nope. Not using qb-core since 2022 Nov
