### ISSUE TITLE
[BUG] Armor not saving?

### ISSUE THREAD

**Issue by nzkfc** [qbcore-framework/qb-smallresources#293]
**Describe the bug**
Players put on half or full armor, run around for an hour without taking any damage, log out, come back next day and armor is missing 100%

**To Reproduce**
1. Use armor
2. Run around for a bit (say more then 20mins) 
3. Close Fivem
4. Wait 5 mins
5. Rejoin server

**Expected behavior**
Armor should be saved to meta

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: A few weeks
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target]
 - Have you renamed `qb-` to something custom?No 

**Additional context**
This seems to be an issue for a good year+ now, i'm not sure why these kind of scripts exist: https://github.com/Nathan-FiveM/qb-armor as im sure it can be handled by QB-Core internally.

There also seems to be tons of snippets to implement this also :S

**Comment by LaserFeesh** [comment]
I have this issue also.  For my character it saved it at some point but now every time I relog it would go back to 75 even if it's all gone. Doesn't seem to update the metadata.

**Comment by ItssJxstnDe** [comment]
Same!

**Comment by nzkfc** [comment]
Fixed mine by replacing fivem-appearance with illineium-appearance as he
did some fixes with qbcore for it, just female health being 175 now.

**Comment by ItssJxstnDe** [comment]
I have illenium too but No saving

**Comment by ChrizsTTV** [comment]
still no fix

**Comment by Pyth3rEx** [comment]
+1
also mentioned in https://github.com/qbcore-framework/qb-core/issues/950

**Comment by Pyth3rEx** [comment]
Referring the fix for the issue:
https://github.com/qbcore-framework/qb-core/issues/950#issuecomment-1964858534
