### ISSUE TITLE
seatbelts not working [BUG]

### ISSUE THREAD

**Issue by OBDre** [qbcore-framework/qb-smallresources#298]
**Describe the bug**
when you press b to put the seat belt on you hear the sound but icon doesnt go away.

**Comment by deyoung87** [comment]
Seat Belt not working for me either but i did notice that seat belt work for another person in the server

**Comment by stevensonmediagroup** [comment]
Hearing the noise when pressing the keybind. Still am ejected. Sometimes but not always the /toggleseatbelt command works to keep me in the vehicle.

**Comment by Sreve00** [comment]
Anyone ever find a fix..works for everyone else but me which runs the server
