### ISSUE TITLE
[BUG] Reticle

### ISSUE THREAD

**Issue by HighCaliber50** [qbcore-framework/qb-smallresources#306]
**Describe the bug**
For some reason, the reticle is showing up in my server. Its set to be off, it used to be off, but out of nowhere it just started showing up again, not sure if anyone else is experiencing this.

Config.Disable = {
    disableHudComponents = {1, 2, 3, 4, 7, 9, 13, 14, 19, 20, 21, 22}, -- Hud Components: https://docs.fivem.net/natives/?_0x6806C51AD12B83B8
    disableControls = {37}, -- Controls: https://docs.fivem.net/docs/game-references/controls/
    displayAmmo = true -- false disables ammo display

This is how im set up at the moment so it should not be visable.

**Comment by SoulReaper4720** [comment]
Take out the other Config.Disable. They have it in there twice for some reason.

**Comment by HighCaliber50** [comment]
> Take out the other Config.Disable. They have it in there twice for some reason.

is it in the config.lua? I only see it once in there

**Comment by Bakisito** [comment]
check your hudcomponents.lua @HighCaliber50

**Comment by HighCaliber50** [comment]
> check your hudcomponents.lua @HighCaliber50

what am i looking for in there bro?

**Comment by Bakisito** [comment]
> > check your hudcomponents.lua @HighCaliber50
> 
> what am i looking for in there bro?

Is it the same as in the repository? have you edited it?
Try to update your qb-smallresources

**Comment by MrAladin-afs** [comment]
i having this issu you have solution?
