### ISSUE TITLE
[BUG] Removeentities error

### ISSUE THREAD

**Issue by KSJDiamondGaming** [qbcore-framework/qb-smallresources#312]
**Describe the bug**
![Objects](https://user-images.githubusercontent.com/83096833/209727785-89cf6489-8565-4480-ac00-fb063d77f26f.png)

![20221227222048_1](https://user-images.githubusercontent.com/83096833/209727807-51882392-fb63-4b99-921e-7a7d551ec120.jpg)

Since latest update. Config.objects doesnt seem to be taking effect. Unless of course i havent updated correctly. but this seems to be dafault.

**Comment by kaneit** [comment]
doesn't work for me either.
even on a vanilla build
