### ISSUE TITLE
[BUG] Reticle is hidden for Sniper Rifles.

### ISSUE THREAD

**Issue by daveayee** [qbcore-framework/qb-smallresources#313]
Reticle is is missing when using sniper rifle. Is there a way to hide the reticle/crosshair on all weapons except for the sniper rifles?

**Questions (please complete the following information):**
 - When you last updated: last week
 - Are you using custom resource? which ones? No
 - Have you renamed `qb-` to something custom? No

**Comment by Bakisito** [comment]
done @daveayee
