### ISSUE TITLE
[BUG] Weapon Whip is back

### ISSUE THREAD

**Issue by SKITTLE6969** [qbcore-framework/qb-smallresources#315]
**Describe the bug**
Weapon Whip is back after this update

**To Reproduce**
aim to head of someone, go close to that player and shoot. Instead of shooting the player he just hit with the weapon & one hit dead

**Expected behavior**

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: vanilla 
 - Are you using custom resource? which ones? no
 - Have you renamed `qb-` to something custom? no

**Additional context**

**Comment by AnishBplayz** [comment]
Does this still persist ?

**Comment by AnishBplayz** [comment]
Sure but as i remember it was removed so i did make a PR referencing the issue

https://github.com/qbcore-framework/qb-smallresources/pull/381

This is the PR
