### ISSUE TITLE
[BUG] Seat shuffle not working

### ISSUE THREAD

**Issue by Krisb239** [qbcore-framework/qb-smallresources#317]
**Describe the bug**
Seat shuffle is no longer working after latest update 

**To Reproduce**
1. getting in car immediately shuffles you to the driver seat. If you have someone in the car and the driver gets out and locks the car the passenger will shuffle to the drivers seat and will be locked in the car.

**Expected behavior**
when getting in a car you stay in the seat you initially get in.

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] 2 days ago
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] no
 - Have you renamed `qb-` to something custom? [e.g. yes/no] no

**Comment by Bakisito** [comment]
I just installed a fresh qbcore, everything fine @Krisb239
