### ISSUE TITLE
[BUG][Error] consumeables.lua

### ISSUE THREAD

**Issue by Chaosfelix4451** [qbcore-framework/qb-smallresources#318]
**Error**
Updated the ressurce and the error occured in console.
**To Reproduce**
1. Download latest version
2. Replace the old one

**Expected behavior**
No Server error

**Screenshots**
![image](https://user-images.githubusercontent.com/46029764/210181680-6ef62f44-9b6f-47ff-a7fa-ffd021c9165f.png)

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week]
 Just before
 - Have you renamed `qb-` to something custom? [e.g. yes/no]
no
**Additional context**

**Comment by Bakisito** [comment]
What version of the old qb-smallresources did you have?

**Comment by Chaosfelix4451** [comment]
Not sure but my qb-core version is:  (1.2.1)

**Comment by Bakisito** [comment]
> Not sure but my qb-core version is: (1.2.1)

**Check your resources\[qb]\qb-smallresources\fxmanifest.lua and compare it with the one in the repository.**
https://github.com/qbcore-framework/qb-smallresources/blob/76f310d2178dd3e79d062239f90dd08c15632c2b/fxmanifest.lua#L4-L5

**Comment by beyond420** [comment]
im getting the same problem and i have the newest core and the newest smallresource i went back an update for the smallresource to fix it for now but im recieving the same error code

**Comment by hus7lazz** [comment]
I expirience the same issue, fresh installation of verion 1.3.0 
[https://imgur.com/a/OC8wjbE](url)
