### ISSUE TITLE
[BUG] - Weapon pull out and put away animation not working. Drug effects too :(

### ISSUE THREAD

**Issue by the-revival-public** [qbcore-framework/qb-smallresources#320]
There is no animation when pulling a weapon out 
Joint and drug effects seem to have gone.
My only complaints up to now..

**Expected behavior**
- Pull out weapon with an animation for realistic purposes
- Drug effects to shake the screen and change colour etc

**Screenshots**

**Questions (please complete the following information):**
 - Up to date qb-core and qb-smallresources
- I don't think any of my other resources affect this
 - Have you renamed `qb-` to something custom? NO

**Comment by Bakisito** [comment]
I just installed a fresh qbcore, everything fine
