### ISSUE TITLE
Development NetEvent name in Production

### ISSUE THREAD

**Issue by snalye** [qbcore-framework/qb-smallresources#321]
In consumables.lua both Client and Server, the AddParachute NetEvent is titled, `qb-smallpenis:server:AddParachute`

https://github.com/qbcore-framework/qb-smallresources/blob/b2b83f5f695f38586287f1b722f20f7803c236a3/client/consumables.lua#L419
https://github.com/qbcore-framework/qb-smallresources/blob/b2b83f5f695f38586287f1b722f20f7803c236a3/server/consumables.lua#L106

**Comment by Bakisito** [comment]
That's a Easter egg bro! 🤣🤣 @snalye

**Comment by Bakisito** [comment]
@snalye Done!
