### ISSUE TITLE
[BUG] Hunger and thirst still ticking after player death

### ISSUE THREAD

**Issue by Nanorithm** [qbcore-framework/qb-smallresources#328]
**Describe the bug**
After a player dies from hunger/thirst, they are knocked unconscious but the damage ticking doesn't stop at this point. Causing the player to full die within seconds rather than the configured bleed out time.

**To Reproduce**
1. Die from hunger
2. Damage keeps ticking after death

**Expected behavior**
After being knocked out from hunger, the damage ticks stop so that the bleed out timer can run fully.

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] Yesterday
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] no
 - Have you renamed `qb-` to something custom? [e.g. yes/no] no

**Comment by DuoTheDev** [comment]
Currently looking into this issue.
