### ISSUE TITLE
[BUG] Ejected from vehicle, can't access it anymore without being launched out again (error in F8 console)

### ISSUE THREAD

**Issue by Rhydium** [qbcore-framework/qb-smallresources#345]
**Describe the bug**
I got ejected from my vehicle, after trying to get back into it I was ejected again. When checking the F8 console errors appeared.

**To Reproduce**
1. Crash a vehicle at high speed
2. Get ejected
3. Try to go back in
4. Get ejected again
5. See error

**Expected behavior**
Being able to re-enter the vehicle without being ejected again

**Screenshots**
https://imgur.com/a/KkIbdiw

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week]
 **Today.**
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target]
 **No.**
 - Have you renamed `qb-` to something custom? [e.g. yes/no]
 **No, I have not.**

**Comment by tom-osborne** [comment]
Can you record a video of this?

**Comment by Rhydium** [comment]
I can't reproduce the issue anymore, so seems like this was some type of weird one time bug.
