### ISSUE TITLE
Cant find where i can change the Vest 

### ISSUE THREAD

**Issue by RaketeOriginal** [qbcore-framework/qb-smallresources#349]
I want to change the vest you put on when using armor / heavy armor .. but i cant find it. Any help?

**Comment by RaketeOriginal** [comment]
better .. i dont want a vest on my ped when im using armor.

**Comment by i-kulgu** [comment]
> I want to change the vest you put on when using armor / heavy armor .. but i cant find it. Any help?

qb-smallresources/client/consumables.lua 

![image](https://user-images.githubusercontent.com/29943243/220362861-93a65b76-2dd4-4fda-a104-6d80fa648f96.png)

**Comment by RaketeOriginal** [comment]
> > I want to change the vest you put on when using armor / heavy armor .. but i cant find it. Any help?
> 
> qb-smallresources/client/consumables.lua
> 
> ![image](https://user-images.githubusercontent.com/29943243/220362861-93a65b76-2dd4-4fda-a104-6d80fa648f96.png)

can a delete this part, if i dont want a visible vest? i want the effect, but no visual feedback :)

**Comment by i-kulgu** [comment]
> > > I want to change the vest you put on when using armor / heavy armor .. but i cant find it. Any help?
> > 
> > 
> > qb-smallresources/client/consumables.lua
> > ![image](https://user-images.githubusercontent.com/29943243/220362861-93a65b76-2dd4-4fda-a104-6d80fa648f96.png)
> 
> can a delete this part, if i dont want a visible vest? i want the effect, but no visual feedback :)

You can delete the lines that i have marked in red box.

**Comment by RaketeOriginal** [comment]
thank so much <3
