### ISSUE TITLE
[BUG] Weapondraw

### ISSUE THREAD

**Issue by TankinTom** [qbcore-framework/qb-smallresources#356]
**Describe the bug**
No matter what weapon (pistol) you use with a holster, it plays the same animation

**To Reproduce**
1. Get a pistol
2. get a holster
3. take out pistol
4. It just appears in your hand

**Expected behavior**
1. Get a pistol
2. get a holster
3. take out pistol
4. It plays the "take out of holster" animation

**Screenshots**
Not really

**Questions (please complete the following information):**
2/6 fresh install of everything

**Additional context**
It used to work months and months ago, then it stopped working fro no reason.

**Comment by Veolene** [comment]
try removing the following line in fxmanifest.lua

`use_experimental_fxv2_oal 'yes'`

no idea what the specifics are here, i just know that this messes up with weapdraw, im just a filthy copypaster

**Comment by Veolene** [comment]
> try removing the following line in fxmanifest.lua
> 
> `use_experimental_fxv2_oal 'yes'`
> 
> no idea what the specifics are here, i just know that this messes up with weapdraw, im just a filthy copypaster

This might cause errors after, if it does, replace binoculars.lua with this one. This is the old binoculars.lua from a couple months ago. 

https://cdn.discordapp.com/attachments/884485370614530141/1081169026987860048/binoculars.lua

**Comment by TankinTom** [comment]
Same issue, no error though.

**Comment by Veolene** [comment]
Okay, disregard what I wrote then, get another clean install and use this weapdraw.lua. The difference will be that it will no longer be dependent on qb-inventory but you will gain roughly 0.05ms because it has to check with a thread instead of being activated by the inventory system.


https://cdn.discordapp.com/attachments/884485370614530141/1081205103710720040/weapdraw.lua

if this doesnt work then i am afraid i have tried all i could :(

**Comment by Veolene** [comment]
add 
`local QBCore = exports['qb-core']:GetCoreObject()` on the top that will get rid of the issue

**Comment by AnishBplayz** [comment]
Seems good to close since this error doesn't exist anymore unless you have renamed your inventory anything else than **qb-inventory**
