### ISSUE TITLE
[BUG] No Reticle

### ISSUE THREAD

**Issue by KingRyuShin** [qbcore-framework/qb-smallresources#358]
I'm trying everything, i have no reticle ingame.

My disable line is like that : `disableHudComponents = {1, 2, 3, 4, 7, 9, 13, 19, 20, 21, 22},`

Tryed reinstalling GTA, nothing there also..
I've checked all my files with notepad++ for HideHudComponentThisFrame and there is nothing else
I've no custom script that do use : HideHudComponentThisFrame

**Comment by Bakisito** [comment]
Were you able to solve the problem?

**Comment by KingRyuShin** [comment]
> 

Yeah it was my NVE graphic pack that had a mod inside the FiveM folder that was disabling the reticle
