### ISSUE TITLE
[BUG] No Traffic Spawning

### ISSUE THREAD

**Issue by JordanBScott** [qbcore-framework/qb-smallresources#363]
**Describe the bug**
The density is not working upon initial restart. I can fix the issue by restarting qb-smallresources manually after each restart, but I should not have to. Without restarting the script manually there are no driving npc's.

**To Reproduce**
1. Configure density in qb-smallresources/config
2. Restart server
3. Load into server and see that there are no npc's driving around

**Expected behavior**
There should be locals driving around depending on the configuration of the density in the config.lua file

**Screenshots**
This metal video will show the vehicles driving towards a player but never showing up. Just disappearing.
(https://medal.tv/games/gta-v/clips/11o4UqhLSMXKP1/d1337DF5wu3Z?invite=cr-MSw4R3AsMTI3NTgxODQ3LA)

**Questions (please complete the following information):**
 - When you last updated: 3 Days Ago
 - Are you using custom resource? which ones? Not for qb-smallresources
 - Have you renamed `qb-` to something custom? No

**Additional context**
N/A

**Comment by GhzGarage** [comment]
This seems to be caused by some external factor because I use this system on my own server which restarts 3 times a day with no issue of traffic not showing up

**Comment by AnishBplayz** [comment]
It could be some external script interfering with your server...
