### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Epsilona** [qbcore-framework/qb-smallresources#367]
**Describe the bug**
I cannot press the button "X" the get my handsup using the qb-smallresources. But the /hu works for me.

**To Reproduce**
1. Go to 'fivem'
2. Click on 'X'
3. See error

**Expected behavior**
My hands would go up in an animation.

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: 2 weeks ago
 - Are you using custom resource? which ones? qb-target
 - Have you renamed `qb-` to something custom? No

**Additional context**

**Comment by megajkobe** [comment]
Do you get any error in f8 menu or in the console log?

**Comment by Epsilona** [comment]
> Do you get any error in f8 menu or in the console log?

No but its solved, i had to add this in the file for handsup: local animDict = "missminuteman_1ig_2"
local anim = "handsup_base"
local handsup = false
RegisterCommand('hu', function()
    local ped = PlayerPedId()
    if not HasAnimDictLoaded(animDict) then
        RequestAnimDict(animDict)
        while not HasAnimDictLoaded(animDict) do
            Wait(10)
        end
    end
    handsup = not handsup
    if exports['qb-policejob']:IsHandcuffed() then return end
    if handsup then
        TaskPlayAnim(ped, animDict, anim, 8.0, 8.0, -1, 50, 0, false, false, false)
        exports['qb-smallresources']:addDisableControls(Config.disableHandsupControls)
    else
        ClearPedTasks(ped)
        exports['qb-smallresources']:removeDisableControls(Config.disableHandsupControls)
    end
end, false)

exports('getHandsup', function() return handsup end)

RegisterKeyMapping('hu', 'Hands Up/Down', 'keyboard', 'X')

**Comment by iafondo** [comment]
did you delete dp emotes?

**Comment by Epsilona** [comment]
> 

No i just added this in the end "RegisterKeyMapping('hu', 'Hands Up/Down', 'keyboard', 'X')"

**Comment by Eridau** [comment]
Can confirm this is a problem on my server as well.

**Comment by AnishBplayz** [comment]
Create a PR if not done yet with the fix
