### ISSUE TITLE
[BUG] qb-smallresources\client\consumables.lua

### ISSUE THREAD

**Issue by theghostglitch** [qbcore-framework/qb-smallresources#374]
consumables:client:UseJoint in consumables.lua does not work for females. There needs to be a check here for gender.
The emote smokeweed is male only. The emote for females is smokeweed2.
This also causes the script to fail and mental status does not go down.

**To Reproduce**
Use a joint from inventory as a female character.

**Expected behavior**
The smokeweed animation should play and mental should go down.

**Questions (please complete the following information):**
 - When you last updated: Today
 - Are you using custom resource? which ones? None that effect qb-smallresources.
 - Have you renamed `qb-` to something custom? No

**Comment by theghostglitch** [comment]
Little hint because I'm working on this myself. Gender can be obtained with:
local gender = QBCore.Functions.GetPlayerData().charinfo.gender

I'm just having a hard time finding where the event 'animations:client:SmokeWeed' is defined, because it seems to be an animation timer?

**Comment by theghostglitch** [comment]
I did a little hack to fix. Apparently it was relying on code from dpemote instead of rpemote. So I removed the Timer/Stress relief command at the end and added the gender check. Here's my re-code if you want to use/build off of it.

`RegisterNetEvent('consumables:client:UseJoint', function()
	local gender = QBCore.Functions.GetPlayerData().charinfo.gender
    QBCore.Functions.Progressbar("smoke_joint", Lang:t('consumables.joint_progress'), 1500, false, true, {
        disableMovement = false,
        disableCarMovement = false,
        disableMouse = false,
        disableCombat = true,
    }, {}, {}, {}, function() -- Done
        TriggerEvent("inventory:client:ItemBox", QBCore.Shared.Items["joint"], "remove")
        if IsPedInAnyVehicle(PlayerPedId(), false) then
            TriggerEvent('animations:client:EmoteCommandStart', {"smoke3"})
        elseif gender == 1 then
            TriggerEvent('animations:client:EmoteCommandStart', {"smokeweed2"})
		else
			TriggerEvent('animations:client:EmoteCommandStart', {"smokeweed"})
        end
        TriggerEvent("evidence:client:SetStatus", "weedsmell", 300)
		TriggerServerEvent('hud:server:RelieveStress', math.random(20, 50))
    end)
end)`

**Comment by theghostglitch** [comment]
I did a little re-code to fix the issue, if you want to use/work around it.

RegisterNetEvent('consumables:client:UseJoint', function()
	local gender = QBCore.Functions.GetPlayerData().charinfo.gender
    QBCore.Functions.Progressbar("smoke_joint", Lang:t('consumables.joint_progress'), 1500, false, true, {
        disableMovement = false,
        disableCarMovement = false,
        disableMouse = false,
        disableCombat = true,
    }, {}, {}, {}, function() -- Done
        TriggerEvent("inventory:client:ItemBox", QBCore.Shared.Items["joint"], "remove")
        if IsPedInAnyVehicle(PlayerPedId(), false) then
            TriggerEvent('animations:client:EmoteCommandStart', {"smoke3"})
        elseif gender == 1 then
            TriggerEvent('animations:client:EmoteCommandStart', {"smokeweed2"})
		else
			TriggerEvent('animations:client:EmoteCommandStart', {"smokeweed"})
        end
        TriggerEvent("evidence:client:SetStatus", "weedsmell", 300)
		TriggerServerEvent('hud:server:RelieveStress', math.random(20, 50))
    end)
end)

**Comment by AnishBplayz** [comment]
@theghostglitch create a PR if you haven't yet
