### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 300grim** [qbcore-framework/qb-smallresources#388]
**Describe the bug**
I have removed "14" from my disabled hud components in my config, and don't see it anywhere listed in my hudcomponents.Lua, however I still get no reticle on my weapons. 

**To Reproduce**
1. install qb-smallresources
2. remove "14" from disabledhudcomponents
3. Restart server 
4. aim your gun to see if there is a reticle 
4. no error listed, no reticle shown. followed all steps listed as the remedy online.
 
Expected behavior: See my reticle when aiming my firearm. 

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] 1 month ago
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] none that effect smallresources
 - Have you renamed `qb-` to something custom? [e.g. yes/no] no

**Comment by allChuu** [comment]
It's in config.lua of smallresources that you will find 

`Config.Disable = {
    disableHudComponents = {1, 2, 3, 4, 7, 9, 13, 14, 19, 20, 21, 22}, -- Hud Components: https://docs.fivem.net/natives/?_0x6806C51AD12B83B8`

Their you remove the 14

**Comment by 300grim** [comment]
> It's in config.lua of smallresources that you will find
> 
> `Config.Disable = { disableHudComponents = {1, 2, 3, 4, 7, 9, 13, 14, 19, 20, 21, 22}, -- Hud Components: https://docs.fivem.net/natives/?_0x6806C51AD12B83B8`
> 
> Their you remove the 14

i have already removed the 14, still no reticle
