### ISSUE TITLE
[BUG] Weapon DRAW doesnt work [qb-inventory / jpr-inventario]

### ISSUE THREAD

**Issue by allChuu** [qbcore-framework/qb-smallresources#393]
**Describe the bug**
I change qb-inventory for jpr-inventario wich pratically use the same events has qb-inventory.

**To Reproduce**
Just with - qb-inventory weapon draw works finr
with - jpr-inventory it doesnt, the weapon just appear in the hand their is no error.

**Expected behavior**
Expect that if you use a weapon it draw it, and if it draw it their should be an animation.

**Screenshots**
_NONE._

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] - Last version
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] - yes - jpr_inventario
 - Have you renamed `qb-` to something custom? [e.g. yes/no] - Absolutly not.

**Additional context**
I find it weird and not understandable why the weapon draw that is an "external" resources work only with qb-inventory knowing that events regarding the use of item is in qbcore and not especially in inventory.

**Comment by virtuseee** [comment]
Im having the same issue did u find a fix?
