### ISSUE TITLE
[BUG] attempt to index a nil value when spawning

### ISSUE THREAD

**Issue by PCL-CrisKolkman** [qbcore-framework/qb-smallresources#397]
Below error is seen when spawning in the server, it doesn't matter if you choose last location or another location, each time spawned at the same location (170.05, -989.22, 30.09) and this error in the F8 console:

![image](https://github.com/qbcore-framework/qb-smallresources/assets/97805195/13bd9bb8-f1e5-4653-b058-91b5a36b66f2)

**Comment by MafewTM** [comment]
I'm having trouble recreating this error with a fresh copy of this resource.. Have you tried downloading a fresh copy of qb-smallresources?
