### ISSUE TITLE
Hearing Radio of Wanted System / Seeing Blinking GPS

### ISSUE THREAD

**Issue by PeanutSyrup** [qbcore-framework/qb-smallresources#4]
Picture Example: https://media.discordapp.net/attachments/854912490788880414/855802420898037820/unknown.png?width=981&height=676
After shooting while in vehicle or if you get out and shoot then get back in you will see the GPS flash red and blue, as well occasionally here the radio "beep" as if the Local AI are talking (though there is no talking and it's just the radio sound). This is with a fresh install of the latest qb-smallresources script.

**Comment by GhzGarage** [comment]
This was fixed with this commit https://github.com/qbcore-framework/qb-smallresources/commit/7aafd43a08da2f0cbe3f096d4a783dd41e15b4c3
