### ISSUE TITLE
[BUG] No such export AddTargetBone in resource qb-target

### ISSUE THREAD

**Issue by Schweinejaeger** [qbcore-framework/qb-smallresources#401]
**Describe the bug**
With the new Update i get this error Message in the log from the file client/vehiclepush.lua:70: 
![grafik](https://github.com/qbcore-framework/qb-smallresources/assets/75898028/84bfa5c7-07e4-40ee-9cf1-ea505b36d970)
I do not use qb-target. Since this repo do not has target as dependency, pls rework the code, that i works with and without qb-target. I rollback to an older version and it works without any problem, cause there was it made with "normal" qb-ressources.

**To Reproduce**
1. Do not have qb-target installed.
2. Start the Server with the newest version of this file.
3. Load as client into game. You find the bug in the console after spawn.

**Expected behavior**
To Work without qb-target.

**Comment by djraymond1** [comment]
pls reinstal qb-target the script is no dependency for qb-smallresources but a lot of scripts on github an tebex use target

**Comment by Schweinejaeger** [comment]
> pls reinstal qb-target the script is no dependency for qb-smallresources but a lot of scripts on github an tebex use target

Sorry, thats not an acceptable answer. It is a bug, because it is not a dependency for the this repo. And so it has to be fixed and not say, install qb-target. We have reasons because we do not want it!
