### ISSUE TITLE
help

### ISSUE THREAD

**Issue by widowx82** [qbcore-framework/qb-smallresources#403]
i am getting tis error and i cant figure out how to fix it. 

1SCRIPT ERROR: @qb-smallresources/client/removeentities.lua:5: bad argument #1 to 'for iterator' (table expected, got nil)^7
handler^7 (^5@qb-smallresources/client/removeentities.lua^7:5)

**Comment by MafewTM** [comment]
This seems to just be an issue on your side with Config.Objects. Check your config.lua and if you cant figure it out, download a fresh copy of this resource.

**Comment by widowx82** [comment]
i did and its still saying the same thing
