### ISSUE TITLE
[BUG] Weapon Draw

### ISSUE THREAD

**Issue by TankinTom** [qbcore-framework/qb-smallresources#407]
**Describe the bug**
NO matter what job or gun or holster you're using, weapon draw remains the same

**To Reproduce**
Take out a weapon

**Expected behavior**
when wearing certain holsters, and having a PD job, get the quick draw animation

**Screenshots**

**Questions (please complete the following information):**
a week ago

No mater what I do, what I change, weapondraw never changes, its always taking it out from the back. I even imported a new version of weapdraw.lua, and it's still doing it. Does anyone have a working version for quick draw?

**Comment by HumiPen** [comment]
Same problem

**Comment by Mati22BE** [comment]
same here

**Comment by el-moxie** [comment]
I have the exact opposite. All my weapons are quick draw no matter what I do to change them. :/

**Comment by SaitaKev** [comment]
We currently have the same problem, even with a healthy database (reinstallation of QbCore / Small resource etc.)
