### ISSUE TITLE
[BUG] Server owners Seatbelt doesnt work when pressing 'b'

### ISSUE THREAD

**Issue by daf4ever** [qbcore-framework/qb-smallresources#413]
**Describe the bug**
Server owners Seatbelt doesnt work. See BUG #298

**To Reproduce**
If you are server owner the seatbelt doesn't work. You can hear the clicking sound but the light doesnt go away and when you drive into something you instantly fly out of the window. It doesnt happen to anyone else but the server owner.

**Expected behavior**
That the seatbelt works for Server Owners

**Questions (please complete the following information):**
When you last updated: 
- October 1st 2023

Are you using custom resource? which ones? 
- I installed QB-Core where this resource was added

**Additional context**
If I type: /toggleseatbelt it works but when pressing 'b' it doesnt. For example it is annoying to write hundred and twenty times  "/toggleseatbelt" in 1 hour when you do a delivery job.

**Comment by KingRyuShin** [comment]
You need the set the ejection event in a thread for the script to work

![Uploading Screenshot_20231009_160709_Samsung Internet.jpg…]()

**Comment by daf4ever** [comment]
Hi KingRyuShin. Can you elaborate? What do you mean with "ejection event in a thread". I downloaded the setup for a QBCore Server and smallresources automatically starts. In config.lua for smallresources I don't find anything with "ejection"

**Comment by Maxhero54** [comment]
my server also   ---- after crash  Eject From Vehicle dont working #415
