### ISSUE TITLE
[BUG] qb-smallresources   -- Eject From Vehicle  dont working 

### ISSUE THREAD

**Issue by Maxhero54** [qbcore-framework/qb-smallresources#415]
i have problem   qb-smallresources   version '1.4.0'
**Eject From Vehicle** is not working, no matter how hard you hit it, you will not be thrown out of the vehicle. This is a good opportunity for players who use it improperly. 

if possible I want this to be fixed and Eject From Vehicle to work and be thrown out of the vehicle...

This worked fine in older versions.. This should be easy to adjust..
.
If so, can you tell me the line or script where I can activate this situation?

thanks

**Comment by Pyth3rEx** [comment]
we need to reopen this

**Comment by Pyth3rEx** [comment]
I got it figured out, you need to update qb-core. Specificaly: `qb-core\server\events.lua`
