### ISSUE TITLE
[BUG] [consumables] SCRIPT ERROR : Execution of native 0000000032ca01c3 .. : Argument at index 1 was null

### ISSUE THREAD

**Issue by allChuu** [qbcore-framework/qb-smallresources#416]
**Describe the bug**

I update my config.lua & consumables client & server with the published refactoring.
Since then, i have this issue in consol. 

It's related to CustomItem, when i uncomment the custom item, or the example. 

I just try to ramake the eat and drink animation for the basic item "water_bottle" so i deleted him from the default and fill every part of the custom side, with bones, anim etc.. it brokes everything. I don't know why.

**Comment by kill3r0nci0** [comment]
i take the same error
