### ISSUE TITLE
[BUG] - NPC/AI Police/Ambulance are active in my city/server

### ISSUE THREAD

**Issue by ChlxeThomson** [qbcore-framework/qb-smallresources#417]
I haven't touched qb-smallresources at all, all the coding for Police etc is all set to FALSE and their peds are blacklisted etc, but yet they seem to be coming after me when ever i shoot a gun or stab someone or beat someone up??????? I haven;t downloaded any other script that would change their behaviour etc. 

**Questions (please complete the following information):**
 - When you last updated: last week
 - Are you using custom resource? - QBcore framework with qb default scripts/resources
 - Have you renamed `qb-` to something custom? - NO

**Additional context**
I cannot seem to find a fix or problem
<img width="1151" alt="Screenshot 2023-10-14 015259" src="https://github.com/qbcore-framework/qb-smallresources/assets/58238399/f64cfba2-7075-4387-8981-93f418488abe">
<img width="1850" alt="Screenshot 2023-10-14 022502" src="https://github.com/qbcore-framework/qb-smallresources/assets/58238399/27176ece-52d6-41e5-8335-e39411237a86">
<img width="1201" alt="Screenshot 2023-10-14 024348" src="https://github.com/qbcore-framework/qb-smallresources/assets/58238399/93bea5d4-602c-4193-8628-e7b27cb1a715">
<img width="307" alt="Screenshot 2023-10-15 212857" src="https://github.com/qbcore-framework/qb-smallresources/assets/58238399/428d3860-9849-40fb-b9eb-398cbf404b70">
<img width="511" alt="Screenshot 2023-10-15 213014" src="https://github.com/qbcore-framework/qb-smallresources/assets/58238399/a5a881c2-2af6-495d-8ff3-d006801320d2">
<img width="374" alt="Screenshot 2023-10-15 213021" src="https://github.com/qbcore-framework/qb-smallresources/assets/58238399/2258b431-a4c9-41bf-92a3-0dc838dc3d83">
<img width="404" alt="Screenshot 2023-10-15 213136" src="https://github.com/qbcore-framework/qb-smallresources/assets/58238399/36efe332-1c99-4e8c-9eeb-ab1008916c7e">

**Comment by ChlxeThomson** [comment]
i have even tried the No-NPC script and it didn't make a difference :(

**Comment by Maxhero54** [comment]
You must be close    
https://prnt.sc/Aw019grsu67u
https://prnt.sc/zg3kWZNG1z5M    qb-smallresource  --->  config.lua  and   ignore.lua   some others ..

**Comment by Bellck** [comment]
/qb-smallresources)/config.lua

Config.DispatchServices = {
    [1] = false, -- Police Vehicles
    [2] = false, -- Police Helicopters
    [3] = false, -- Fire Department Vehicles
    [4] = false, -- Swat Vehicles
    [5] = false, -- Ambulance Vehicles
    [6] = false, -- Police Motorcycles
    [7] = false, -- Police Backup
    [8] = false, -- Police Roadblocks
    [9] = false, -- PoliceAutomobileWaitPulledOver
    [10] = false, -- PoliceAutomobileWaitCruising
    [11] = false, -- Gang Members
    [12] = false, -- Swat Helicopters
    [13] = true, -- Police Boats
    [14] = false, -- Army Vehicles
    [15] = false, -- Biker Backup
}

Ensure all of the above is false.

**Comment by jessemel** [comment]
Im having a similar issue with this, firetrucks are responding, police bikes autospawning at police station all I did was put in the new updated script

**Comment by Maxhero54** [comment]
> Im having a similar issue with this, firetrucks are responding, police bikes autospawning at police station all I did was put in the new updated script

https://github.com/qbcore-framework/qb-smallresources/issues/417#issuecomment-1773216887    did you try this ?

**Comment by jessemel** [comment]
@Maxhero54 yes I did and it did not work, I still see ambulances driving around and police bikes spawning in
