### ISSUE TITLE
[BUG] No such export HasHarness in qb-smallresources

### ISSUE THREAD

**Issue by Bellck** [qbcore-framework/qb-smallresources#425]
**Describe the bug**
When your in a vehicle, using the f1 menu, you cannot swap seats. This is the only error shown on console.

**To Reproduce**
1. Get in a car
2. Open F1 Menu and try change seats
3. Nothing happens
4. Open F8 menu see error

**Expected behavior**
Change seats?

**Screenshots**
https://cdn.discordapp.com/attachments/1166506207788421141/1166506208367218780/image.png

**Questions (please complete the following information):**
 - When you last updated: All server files are updated including all from keymaster.
 - Are you using custom resource? which ones? Jims Mechanic 
 - Have you renamed `qb-` to something custom? [e.g. yes/no] No

**Additional context**
N/A

**Comment by citRaTTV** [comment]
This is working as expected in the latest versions of qb-smallresources & qb-radialmenu. Are you sure qb-smallresources is up to date?

The hasHarness export is here: https://github.com/qbcore-framework/qb-smallresources/blob/main/client/seatbelt.lua#L78
