### ISSUE TITLE
[BUG] AFK TIMER DOESN'T STOP FOR ADMINS

### ISSUE THREAD

**Issue by itzzjd123** [qbcore-framework/qb-smallresources#428]
**Describe the bug**
When I confirm the ignored groups for not being kicked for AFK it still does not work. I as the owner of the server still get kicked after the AFK timer is counting down.

![Screenshot 2023-11-05 085842](https://github.com/qbcore-framework/qb-smallresources/assets/138529607/a82839e3-60d3-4ea8-9dcd-c56b29d6f1c5)

**Comment by SaschaB88** [comment]
Same Issue here.

**Comment by ryan11444** [comment]
same, any fix?

**Comment by citRaTTV** [comment]
This seems to be working correctly on the latest version of the resource. Do you have your permissions added to server.cfg?

**Comment by itzzjd123** [comment]
> This seems to be working correctly on the latest version of the resource. Do you have your permissions added to server.cfg?

@citRaTTV 
![Screenshot 2023-12-12 145807](https://github.com/qbcore-framework/qb-smallresources/assets/138529607/672e0e52-56a2-4ac3-ab0d-8d92b2f68423)

Yes I do.

**Comment by DJJackal** [comment]
Anyone find a solution yet? Or should I just pay for a script that actually works?

**Comment by Llama-Palooza** [comment]
> Anyone find a solution yet? Or should I just pay for a script that actually works?

Does the same for me, it is random though. I stopped caring because the built in afk system is trash. Players can play emotes to bypass the timer.
