### ISSUE TITLE
[BUG]  Can you help me see what you are not allowed to do?

### ISSUE THREAD

**Issue by osdaohdph** [qbcore-framework/qb-smallresources#430]
![image](https://github.com/qbcore-framework/qb-smallresources/assets/140257054/0f3d58ac-3adc-462c-a03f-1ecbbd940f03)

Hello I I have a problem. Can anyone help me resolve this error?

**Comment by JamieT0001** [comment]
I have tested an am unable to replicate. If you are still having this issue please ensure your qb-core is up-to date

**Comment by mfel2k** [comment]
What were you trying to consume at the time? Possible the code for that item is wrong
