### ISSUE TITLE
AI issues

### ISSUE THREAD

**Issue by jessemel** [qbcore-framework/qb-smallresources#432]
I didn't have any issues until I put in the new qb-smallresources update.

All of my settings are false for AI (police, firetrucks, lifegaurds, etc) but they are still showing up in the city. PD motorcycles spawning in at police stations and what not.

![image](https://github.com/qbcore-framework/qb-smallresources/assets/131414893/e59276ad-b482-4f89-825d-b374a0abc79e)

![image](https://github.com/qbcore-framework/qb-smallresources/assets/131414893/d716366b-4b9d-48f7-9b6d-225e5def9704)

![image](https://github.com/qbcore-framework/qb-smallresources/assets/131414893/2bba65cc-fc6c-43fc-9023-2fa8bcf4041a)

![image](https://github.com/qbcore-framework/qb-smallresources/assets/131414893/51b5d47d-a1bd-417d-be74-56db140152fa)

**Comment by citRaTTV** [comment]
If you give qb-smallresources a restart, are you seeing any errors? Latest is working for me w/ these settings.

**Comment by jessemel** [comment]
@citRaTTV no errors at all

**Comment by citRaTTV** [comment]
> @citRaTTV no errors at all
> 

Were you able to resolve this @jessemel

**Comment by Peasmith** [comment]
Same error here.
