### ISSUE TITLE
[BUG] Have to attach and remove harness twice to get out of the vehicle

### ISSUE THREAD

**Issue by YoruNeko-707** [qbcore-framework/qb-smallresources#436]
**Describe the bug**
Each time a player initially uses the harness in a vehicle and then uses it again remove it to get out of said vehicle, they will still be restricted from getting out of the vehicle. They have to use the item a total of 4 times before their character will be able to get out of the vehicle when it should just be two uses.

**To Reproduce**
1. Go to inventory.
2. Use this item 'harness'.
3. See it is attaching the harness.
4. Repeat steps 1-2.
5. See it is removing the harness.
6. Attempt to get out of vehicle.
7. Allow yourself to be stuck.
8. Repeat steps  1-6.
9.  Finally manage to leave vehicle.

**Expected behavior**
The player should be able to leave the vehicle after only one removal.

**Questions (please complete the following information):**
We have the most up to date version of small resources and have not renamed the resource.

**Additional context**
We have only one other script that can possible call the item 'harness' but that feature is set to false. It is Jim-mechanic and we'd prefer to use small resources.

**Comment by brandon1808** [comment]
Did you follow the steps when you where installed the jim mechanic script ?

**Comment by brandon1808** [comment]
@YoruNeko-707 Did you follow the steps when you where installed the jim mechanic script ?

**Comment by YoruNeko-707** [comment]
> @YoruNeko-707 Did you follow the steps when you where installed the jim mechanic script ?

The steps in the jim-mechanic Readme? No, because we have all seatbelt and harness aspects set to false in it. It said it only applies if you are using those features

**Comment by brandon1808** [comment]
> > @YoruNeko-707 Did you follow the steps when you where installed the jim mechanic script ?
> 
> 
> 
> The steps in the jim-mechanic Readme? No, because we have all seatbelt and harness aspects set to false in it. It said it only applies if you are using those features

I removed it because it didn't matter and it worked for me and I didn't have any issues

**Comment by YoruNeko-707** [comment]
I'll try following those instructions and seeing if that fixes it then.

**Comment by YoruNeko-707** [comment]
> > > @YoruNeko-707 Did you follow the steps when you where installed the jim mechanic script ?
> > 
> > 
> > The steps in the jim-mechanic Readme? No, because we have all seatbelt and harness aspects set to false in it. It said it only applies if you are using those features
> 
> I removed it because it didn't matter and it worked for me and I didn't have any issues

I'll try following those instructions and seeing if that fixes it then.

**Comment by YoruNeko-707** [comment]
> > > @YoruNeko-707 Did you follow the steps when you where installed the jim mechanic script ?
> > 
> > 
> > The steps in the jim-mechanic Readme? No, because we have all seatbelt and harness aspects set to false in it. It said it only applies if you are using those features
> 
> I removed it because it didn't matter and it worked for me and I didn't have any issues

Before trying to make changes to smallresources I wanted to test if it really was jim-mechanic. I the entire jim-mechanic resource and the issue still persists. it's not jim-mechanic causing it.

**Comment by brandon1808** [comment]
Did you follow all of the step when you installed Jim machine. I use the harness and I don’t  have any issues

**Comment by YoruNeko-707** [comment]
> Did you follow all of the step when you installed Jim machine. I use the harness and I don’t have any issues

I removed Jim mechanic completely and I'm still having the same problem. Do you use Jim-mechanic's seatbelt and harness system?

**Comment by S3V3N17** [comment]
> Did you follow all of the step when you installed Jim machine. I use the harness and I don’t have any issues

I followed the instructions and restarted the city. The harness won't work at all now and seatbelt gives double notifications.

**Comment by YoruNeko-707** [comment]
> Did you follow all of the step when you installed Jim machine. I use the harness and I don’t have any issues

I followed the instructions and restarted the city. The harness won't work at all now.

**Comment by brandon1808** [comment]
Are you getting any type of errors ?

**Comment by YoruNeko-707** [comment]
> Are you getting any type of errors ?

None whatsoever. I didn't get errors for the small resources issue I described and I'm not getting errors when trying to use the harness through jim....

**Comment by YoruNeko-707** [comment]
Anyone able to help with qb-small resources? It's not Jim and we'd like it to run through qb-smallresources
