### ISSUE TITLE
[BUG] Discord Webhooks

### ISSUE THREAD

**Issue by Rivesudeois** [qbcore-framework/qb-smallresources#438]
**Describe the bug**
I set up the discord webhooks and nothing log in my discord, its not the first scrip I use webhook but its the first time that didnt work

**Expected behavior**
I expected to log in my discord.

**Questions (please complete the following information):**
 - When you last updated: last week
 - Are you using custom resource? which ones? no
 - Have you renamed `qb-` to something custom? no

**Comment by kaynegraham** [comment]
Can you show the code please?

**Comment by Rtextbook** [comment]
lol not really a bug. mine works fine. if you would like help discussing it my discord is rtextbook https://discord.gg/t53zW9e
