### ISSUE TITLE
[BUG] Fireworks doesn't work

### ISSUE THREAD

**Issue by allChuu** [qbcore-framework/qb-smallresources#443]
Hello,

**Describe the bug**
![image](https://github.com/qbcore-framework/qb-smallresources/assets/24990281/cb2ef5b0-53c5-41c1-bd2d-763b878bca9d)

**Additional context**
With the help of chat GPT i modify the following :
```lua
local function fireworkText()
    CreateThread(function()
        while true do
            Wait(0)
            if fireworkTime > 0 and fireworkLoc then
                DrawText3D(fireworkLoc.x, fireworkLoc.y, fireworkLoc.z, Lang:t('firework.time_left')..fireworkTime)
            end
            if fireworkTime <= 0 or fireworkLoc == nil then
                break
            end
        end
    end)
end
```

The error disappear, but the primal trouble remain, no fireworks are launch, no particule effects.

**Comment by rapeurtueur** [comment]
Firework don't work too me too

But I don't have any error

**Comment by Pyth3rEx** [comment]
still no fix?
