### ISSUE TITLE
[BUG] - SCRIPT ERROR: @qb-smallresources/server/entities.lua:6: attempt to index a nil value (global 'Config')

### ISSUE THREAD

**Issue by ChlxeThomson** [qbcore-framework/qb-smallresources#447]
**Describe the bug**
As the title says, i have no idea how to fix it as i am still learning to code with Lua. I haven't edited anything, all i have done is added scripts from [**Apex Studios**](https://astudios.tebex.io/category/escrowed) and configured them to use QB things with the recent changes, i have correctly added the items from them into the **QB-Core/Shared/Items.Lua**, the consumables stuff into QB-Smallresources cause they are scripts for food restaurants 

**Questions (please complete the following information):**
 - When you last updated: - **I haven't, i just installed the recommended latest framework build & started a new server**
 - Are you using custom resource? - **No**
 - Have you renamed `qb-` to something custom? - **No**

**Additional context**
If someone could help me that would be great, thanks

**Screenshots**
<img width="684" alt="Screenshot 2024-01-06 060205" src="https://github.com/qbcore-framework/qb-smallresources/assets/58238399/246f832b-4d4a-4c8d-b5ae-c614d8425c9e">
<img width="735" alt="Screenshot 2024-01-06 060234" src="https://github.com/qbcore-framework/qb-smallresources/assets/58238399/39befe44-37fc-46b1-a816-788b79dd14aa">

**Comment by kaynegraham** [comment]
try and reinstall the resource.

**Comment by ChlxeThomson** [comment]
> try and reinstall the resource.

Fixed it thank you for the heads up
