### ISSUE TITLE
[BUG] Armor doesnt Save on F8 Quit

### ISSUE THREAD

**Issue by ChrizsTTV** [qbcore-framework/qb-smallresources#455]
**Describe the bug**
Armor doesnt save in the Metadata of the Player when F8 Quitting.

**To Reproduce**
1. Use Armor
3. F8 Quit
5. Rejoin the Server
6. No Armor on the Char

**Expected behavior**
After Reconnecting the Armor should be saved.

**Comment by Pyth3rEx** [comment]
double #293

**Comment by Pyth3rEx** [comment]
Referring the fix for the issue:
https://github.com/qbcore-framework/qb-core/issues/950#issuecomment-1964858534

**Comment by Pyth3rEx** [comment]
lol
