### ISSUE TITLE
Play a voice while seatbelt not attached

### ISSUE THREAD

**Issue by shoaib119p1** [qbcore-framework/qb-smallresources#471]
Please add an option for seatbelt that when player has not attached their seatbelt an ogg or mp3 voice should be played saying please attach or use your seatbelt

**Comment by ChlxeThomson** [comment]
> Please add an option for seatbelt that when player has not attached their seatbelt an ogg or mp3 voice should be played saying please attach or use your seatbelt

Ngl that would be so annoying, just use the default audio that comes with the framework
