### ISSUE TITLE
Teleport locations not showing

### ISSUE THREAD

**Issue by Xodius** [qbcore-framework/qb-smallresources#60]
I definitely had this working at one point, but it seems to have stopped completely now. I am using the pure vanilla script of here with no changes.

1. Go to 909.49, -1589.22, 30.51, 92.24 for the coke entrance (I've been to all the pre-done locations and there are no TP's there)
2. Note that it's missing

**Comment by GhzGarage** [comment]
![image](https://user-images.githubusercontent.com/57848836/131302230-b8651227-476b-40a3-8f8f-48f9767d69f6.png)

**Comment by squeaks1811** [comment]
@Xodius how and what did u need to make the coke once you are inside
