### ISSUE TITLE
nice easy function handsup

### ISSUE THREAD

**Issue by OxGhali** [qbcore-framework/qb-smallresources#69]
Citizen.CreateThread(function()
    local dict = "missminuteman_1ig_2"
    
	RequestAnimDict(dict)
	while not HasAnimDictLoaded(dict) do
		Citizen.Wait(100)
	end
    local handsup = false
	while true do
		Citizen.Wait(0)
		if IsControlJustPressed(1, 323) then 
            if not handsup then
                TaskPlayAnim(GetPlayerPed(-1), dict, "handsup_enter", 8.0, 8.0, -1, 50, 0, false, false, false)
                handsup = true
            else
                handsup = false
                ClearPedTasks(GetPlayerPed(-1))
            end
        end
    end
end)

**Comment by GhzGarage** [comment]
We already have a handsup?

**Comment by notapteryx** [comment]
Yikes "QBCORE" STORE

**Comment by evanillaa** [comment]
already avariable

**Comment by meistroburger** [comment]
Press X to 'Handsup'

**Comment by LifeStyleRolePlay** [comment]
Yeah small resources already has a hands up
