### ISSUE TITLE
Adding Liquor effects 

### ISSUE THREAD

**Issue by sandunisuru** [qbcore-framework/qb-smallresources#86]
It's nice if we can add some drunken effects to liquors.

**Comment by sandunisuru** [comment]
I have modified this script to add that. If you are Okay, I can add PR with that

**Comment by shehanwijeyaweera** [comment]
> 
> 
> I have modified this script to add that. If you are Okay, I can add PR with that

I'm searching for a script that can change the camera angel of the player to best imitate the drunken effect.  I was only able to add a blur effect with high contrast color changes. Does your script do that as well @sandunisuru.

**Comment by sandunisuru** [comment]
@shehanwijeyaweera yes, it shakes the camera and gives drunken animation for the player as well
